In [1]:
import pandas as pd

In [10]:
# parkinson_exp_dict = {
#     'E-GEOD-7307':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-7307/E-GEOD-7307_A-AFFY-44-analytics.tsv',
#     'E-MEXP-1416':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-MEXP-1416/E-MEXP-1416_A-AFFY-54-analytics.tsv',
#     'E-GEOD-7621':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-7621/E-GEOD-7621_A-AFFY-44-analytics.tsv',
#     'E-GEOD-20168':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-20168/E-GEOD-20168_A-AFFY-33-analytics.tsv',
#     'E-GEOD-20333':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-20333/E-GEOD-20333_A-AFFY-41-analytics.tsv'}

# def data_reader(experiment_id:str):
#     if experiment_id in parkinson_exp_dict:
#         url = parkinson_exp_dict[experiment_id]
# #         print(url)
#         df = pd.read_csv(url,sep='\t')
#         return df
#     else:
#         raise ValueError ("Experiment ID does not belong to Parkinson's disease")

In [ ]:
exps = ['E-MEXP-1416', 'E-GEOD-20333', 'E-GEOD-7307', 'E-GEOD-7621', 'E-GEOD-20168']

# groups related to parkinson
group_ids = [
    'g2_g1',
    'g4_g3',
    'g83_g17',
    'g82_g16',
    'g72_g15',
    'g63_g14',
    'g48_g13',
    'g1_g2',]

In [2]:
exp1 = "C:\\Users\\kriti\\Downloads\\E-MEXP-1416_A-AFFY-54-analytics.tsv"
exp2 = "C:\\Users\\kriti\\Downloads\\E-GEOD-20333_A-AFFY-41-analytics.tsv"
exp3 = "C:\\Users\\kriti\\Downloads\\E-GEOD-7307_A-AFFY-44-analytics.tsv"
exp4 = "C:\\Users\\kriti\\Downloads\\E-GEOD-7621_A-AFFY-44-analytics.tsv"
exp5 = "C:\\Users\\kriti\\Downloads\\E-GEOD-20168_A-AFFY-33-analytics (1).tsv"

In [4]:
# E-MEXP-1416
df1 = pd.read_csv(exp1, sep='\t')
df1

,Gene ID,Gene Name,Design Element,g2_g1.p-value,g2_g1.t-statistic,g2_g1.log2foldchange,g4_g3.p-value,g4_g3.t-statistic,g4_g3.log2foldchange
0,ENSG00000000003,TSPAN6,g2995860_3p_at,NaN,1.703524,1.0,0.522520,1.241137,0.9
1,ENSG00000000005,TNMD,g11545882_3p_at,NaN,-0.329159,-0.1,NaN,0.575565,0.1
2,ENSG00000000419,DPM1,g4503362_3p_at,NaN,2.286994,2.0,0.997115,-0.006181,0.0
3,ENSG00000000457,SCYL3,g9967093_3p_s_at,NaN,1.762578,1.6,0.723872,0.678925,0.4
4,ENSG00000000460,C1orf112,g8922604_3p_a_at,NaN,-1.018646,-0.1,NaN,-0.285732,-0.1
...,...,...,...,...,...,...,...,...,...
20978,ENSG00000288611,NPBWR1,Hs.248117.0.S1_3p_at,NaN,-3.143602,-0.6,NaN,-1.394599,-0.4
20979,ENSG00000288642,CDR1,g4757963_3p_at,NaN,-0.590396,-0.1,NaN,1.053423,0.2
20980,ENSG00000288649,ACTL10,Hs.191063.0.S1_3p_at,NaN,-2.066269,-0.4,NaN,0.415094,0.1
20981,ENSG00000288658,NaN,Hs.146225.0.A1_3p_at,NaN,4.611951,1.1,NaN,1.125041,0.3
20982,ENSG00000288701,PRRC2B,Hs.108945.0.S2_3p_a_at,NaN,2.388381,1.2,NaN,0.309761,0.1

In [5]:
# E-GEOD-20333
df2 = pd.read_csv(exp2, sep='\t')
df2

,Gene ID,Gene Name,Design Element,g2_g1.p-value,g2_g1.t-statistic,g2_g1.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,NaN,-2.336661,-0.5
1,ENSG00000000005,TNMD,220065_at,NaN,1.738032,0.2
2,ENSG00000000419,DPM1,202673_at,0.129577,-3.063216,-0.9
3,ENSG00000000971,CFH,213800_at,0.772056,-0.368670,-0.1
4,ENSG00000001084,GCLC,202922_at,NaN,-1.117266,-0.2
...,...,...,...,...,...,...
7601,ENSG00000281708,ERC2-IT1,208247_at,NaN,2.783343,0.4
7602,ENSG00000282608,ADORA3,206171_at,NaN,1.918752,0.3
7603,ENSG00000286522,H3C2,208576_s_at,NaN,-0.680612,-0.1
7604,ENSG00000287080,H3C3,208577_at,NaN,1.063646,0.1
7605,ENSG00000288642,CDR1,207276_at,NaN,-0.902650,-0.2

In [6]:
#E-GEOD-7307
df3 = pd.read_csv(exp3, sep='\t')
df3

,Gene ID,Gene Name,Design Element,g12_g5.p-value,g12_g5.t-statistic,g12_g5.log2foldchange,g12_g6.p-value,g12_g6.t-statistic,g12_g6.log2foldchange,g3_g2.p-value,...,g78_g21.log2foldchange,g82_g16.p-value,g82_g16.t-statistic,g82_g16.log2foldchange,g83_g17.p-value,g83_g17.t-statistic,g83_g17.log2foldchange,g88_g101.p-value,g88_g101.t-statistic,g88_g101.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.971106,0.318608,0.0,1.066129e-03,-5.150820,-0.5,NaN,...,0.1,0.116127,-2.070131,-0.6,0.095392,-2.262206,-0.5,0.128541,-2.115570,-0.7
1,ENSG00000000005,TNMD,220065_at,0.980500,-0.200143,0.0,NaN,0.105347,0.0,NaN,...,-2.1,NaN,1.173922,0.3,0.937077,0.109329,0.0,0.079293,-2.517706,-2.2
2,ENSG00000000419,DPM1,202673_at,0.845530,-1.252331,-0.2,5.133205e-01,0.785594,0.1,NaN,...,0.3,NaN,-2.310452,-0.5,NaN,-2.476243,-0.4,0.757479,-0.429641,-0.1
3,ENSG00000000457,SCYL3,205607_s_at,0.958495,0.430481,0.0,2.031028e-05,8.714499,0.9,NaN,...,0.2,NaN,1.837992,0.3,NaN,0.078981,0.0,0.902773,0.178371,0.0
4,ENSG00000000460,C1orf112,220840_s_at,0.850386,1.215919,0.1,7.425598e-08,-17.388069,-1.4,NaN,...,1.3,NaN,0.748839,0.2,NaN,-0.091472,0.0,NaN,0.878721,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21211,ENSG00000288611,NPBWR1,231752_at,0.997469,0.045068,0.0,3.895380e-01,1.036391,0.1,NaN,...,-0.1,NaN,2.305287,0.4,0.004154,5.625858,0.9,0.751258,-0.440696,-0.2
21212,ENSG00000288642,CDR1,207276_at,0.975081,0.246033,0.0,NaN,1.617460,0.1,NaN,...,-0.1,NaN,-0.900018,-0.2,NaN,1.131807,0.3,0.230260,-1.632254,-0.6
21213,ENSG00000288649,ACTL10,232619_at,0.997469,0.038831,0.0,1.215936e-01,1.924384,0.3,NaN,...,0.1,NaN,0.263726,0.0,NaN,2.120215,0.4,0.131633,-2.096190,-0.5
21214,ENSG00000288658,NaN,238727_at,0.886111,-0.979170,-0.1,2.692051e-02,-2.935389,-0.2,NaN,...,0.3,0.032922,-3.347352,-0.8,0.070022,-2.509723,-0.5,NaN,-1.355525,-0.2
21215,ENSG00000288701,PRRC2B,212068_s_at,0.962468,0.381901,0.0,1.181194e-04,6.958088,0.6,NaN,...,-0.1,NaN,1.080686,0.2,NaN,0.288823,0.0,NaN,-2.550236,-0.5

In [7]:
# E-GEOD-7621
df4 = pd.read_csv(exp4, sep='\t')
df4

,Gene ID,Gene Name,Design Element,g1_g2.p-value,g1_g2.t-statistic,g1_g2.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.834705,-0.444655,-0.1
1,ENSG00000000005,TNMD,220065_at,NaN,-4.040212,-0.3
2,ENSG00000000419,DPM1,202673_at,0.906982,-0.270559,0.0
3,ENSG00000000457,SCYL3,205607_s_at,0.422994,-1.460597,-0.2
4,ENSG00000000460,C1orf112,220840_s_at,NaN,-0.677550,0.0
...,...,...,...,...,...,...
21044,ENSG00000288611,NPBWR1,231752_at,NaN,-0.893364,-0.1
21045,ENSG00000288642,CDR1,207276_at,0.980924,-0.058132,0.0
21046,ENSG00000288649,ACTL10,232619_at,NaN,-0.298330,0.0
21047,ENSG00000288658,NaN,238727_at,0.525866,-1.196490,-0.4
21048,ENSG00000288701,PRRC2B,212068_s_at,NaN,2.592204,0.2

In [8]:
# E-GEOD-20168
df5 = pd.read_csv(exp5, sep='\t')
df5

,Gene ID,Gene Name,Design Element,g2_g1.p-value,g2_g1.t-statistic,g2_g1.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.623090,0.785727,0.2
1,ENSG00000000005,TNMD,220065_at,NaN,2.179824,0.2
2,ENSG00000000419,DPM1,202673_at,0.033769,-3.595145,-1.0
3,ENSG00000000457,SCYL3,205607_s_at,NaN,-0.899866,-0.1
4,ENSG00000000460,C1orf112,220840_s_at,NaN,2.572624,0.1
...,...,...,...,...,...,...
12051,ENSG00000287080,H3C3,208577_at,NaN,1.609577,0.1
12052,ENSG00000288569,LINC01949,217342_x_at,NaN,2.409303,0.2
12053,ENSG00000288596,C8orf44,220216_at,NaN,0.950915,0.1
12054,ENSG00000288642,CDR1,207276_at,0.132890,-2.375270,-0.3
12055,ENSG00000288701,PRRC2B,212068_s_at,0.657188,0.714372,0.1

In [3]:
exp_group = {'E-MEXP-1416' : ['g2_g1', 'g4_g3'],
             'E-GEOD-20333' : ['g2_g1'],
             'E-GEOD-7307' : ['g83_g17','g82_g16', 'g72_g15', 'g63_g14', 'g48_g13'],
             'E-GEOD-7621' : ['g1_g2'],
             'E-GEOD-20168' : ['g2_g1']}

In [14]:
all_dfs = []
for dfs, exp in zip([df1,df2,df3,df4,df5],exp_group.keys()):
    for group in exp_group[exp]:
        colnames = {f'{group}.p-value' : 'p-value',
                   f'{group}.log2foldchange' : 'log2foldchange'}
        df = dfs[['Gene Name', f'{group}.p-value', f'{group}.log2foldchange']].copy(deep=False)
        df.rename(columns=colnames, inplace=True)
        df['group'] = [group for i in range(len(df))]
        df['experiment'] = [exp for i in range(len(df))]
        all_dfs.append(df)

In [18]:
len(all_dfs)

10

In [20]:
all_dfs[9]

       Gene Name   p-value  log2foldchange  group    experiment
0         TSPAN6  0.623090             0.2  g2_g1  E-GEOD-20168
1           TNMD       NaN             0.2  g2_g1  E-GEOD-20168
2           DPM1  0.033769            -1.0  g2_g1  E-GEOD-20168
3          SCYL3       NaN            -0.1  g2_g1  E-GEOD-20168
4       C1orf112       NaN             0.1  g2_g1  E-GEOD-20168
...          ...       ...             ...    ...           ...
12051       H3C3       NaN             0.1  g2_g1  E-GEOD-20168
12052  LINC01949       NaN             0.2  g2_g1  E-GEOD-20168
12053    C8orf44       NaN             0.1  g2_g1  E-GEOD-20168
12054       CDR1  0.132890            -0.3  g2_g1  E-GEOD-20168
12055     PRRC2B  0.657188             0.1  g2_g1  E-GEOD-20168

[12056 rows x 5 columns]

In [ ]:
all_dfs[1]