# ParkinsonDrugPredictors

## Expression Atlas : 
- To access experimental data for Parkinson's disease in Humans
- Focus on condition : 'Parkinson's disease' vs 'normal' in 'substantia nigra pars reticulata'

In [1]:
import pandas as pd

#### - All experiments for parkinson disease on expression atlas

In [3]:
all_df = pd.read_csv(r"C:\Users\Shubhi Ambast\Downloads\differentialResults.tsv",sep = '\t',encoding='unicode_escape',low_memory=False)

In [4]:
all_df

,Gene,Species,Experiment accession,Comparison,log_2 fold change,Adjusted p-value,t-statistic
0,ENSG00000229807,homo sapiens,E-MEXP-1416,'male' vs 'female' in 'Parkinson's disease',-7.9,0.000060,NaN
1,ENSG00000067048,homo sapiens,E-MEXP-1416,'male' vs 'female' in 'Parkinson's disease',5.7,0.000391,NaN
2,ENSG00000145248,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-4.5,0.000112,NaN
3,ENSG00000137766,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-3.9,0.000012,NaN
4,ENSG00000129824,homo sapiens,E-MEXP-1416,'male' vs 'female' in 'Parkinson's disease',3.9,0.000921,NaN
...,...,...,...,...,...,...,...
995,ENSG00000166111,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-1.3,0.024685,NaN
996,ENSG00000169139,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-1.3,0.025358,NaN
997,ENSG00000121022,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-1.3,0.025630,NaN
998,ENSG00000131966,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-1.3,0.025630,NaN
999,ENSG00000166206,homo sapiens,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,-1.3,0.026027,NaN

In [6]:
all_df['Comparison'].value_counts()

'Parkinson's disease' vs 'normal' in 'substantia nigra pars reticulata'    370
'Parkinson's disease' vs 'normal' in 'substantia nigra pars compacta'      258
'Parkinson's disease' vs 'normal' in 'putamen'                             175
'Parkinson's disease' vs 'normal' in 'globus pallidus'                      82
'Parkinson's disease' vs 'normal' in 'nucleus accumbens'                    35
'Parkinson's disease' vs 'none'                                             27
'male' vs 'female' in 'Parkinson's disease'                                 18
'Parkinson's disease' vs 'normal'                                           17
'Parkinson's disease' vs 'normal' in 'female'                                9
'Parkinson's disease' vs 'normal' in 'male'                                  8
'Parkinson's disease' vs 'control'                                           1
Name: Comparison, dtype: int64

In [7]:
all_df['Comparison'].unique()

array(["'male' vs 'female' in 'Parkinson's disease'",
       "'Parkinson's disease' vs 'normal' in 'substantia nigra pars reticulata'",
       "'Parkinson's disease' vs 'normal' in 'substantia nigra pars compacta'",
       "'Parkinson's disease' vs 'normal' in 'putamen'",
       "'Parkinson's disease' vs 'none'",
       "'Parkinson's disease' vs 'normal' in 'globus pallidus'",
       "'Parkinson's disease' vs 'normal' in 'nucleus accumbens'",
       "'Parkinson's disease' vs 'normal'",
       "'Parkinson's disease' vs 'normal' in 'male'",
       "'Parkinson's disease' vs 'normal' in 'female'",
       "'Parkinson's disease' vs 'control'"], dtype=object)

In [8]:
all_df['Experiment accession'].unique()

array(['E-MEXP-1416', 'E-GEOD-7307', 'E-GEOD-7621', 'E-GEOD-20168',
       'E-MTAB-9950', 'E-GEOD-20333'], dtype=object)

In [6]:
all_df['Experiment accession'].nunique()

6

In [7]:
df = all_df.drop_duplicates(subset=['Experiment accession', 'Comparison'])

In [8]:
dict_df = df.set_index('Comparison').to_dict()['Experiment accession']

In [9]:
dict_df

{"'male' vs 'female' in 'Parkinson's disease'": 'E-MEXP-1416',
 "'Parkinson's disease' vs 'normal' in 'substantia nigra pars reticulata'": 'E-GEOD-7307',
 "'Parkinson's disease' vs 'normal' in 'substantia nigra pars compacta'": 'E-GEOD-7307',
 "'Parkinson's disease' vs 'normal' in 'putamen'": 'E-GEOD-7307',
 "'Parkinson's disease' vs 'none'": 'E-GEOD-7621',
 "'Parkinson's disease' vs 'normal' in 'globus pallidus'": 'E-GEOD-7307',
 "'Parkinson's disease' vs 'normal' in 'nucleus accumbens'": 'E-GEOD-7307',
 "'Parkinson's disease' vs 'normal'": 'E-GEOD-20168',
 "'Parkinson's disease' vs 'normal' in 'male'": 'E-MTAB-9950',
 "'Parkinson's disease' vs 'normal' in 'female'": 'E-MTAB-9950',
 "'Parkinson's disease' vs 'control'": 'E-GEOD-20333'}

In [10]:
df = df.groupby(by=['Experiment accession', 'Comparison'], as_index=False).first()

In [11]:
df

,Experiment accession,Comparison,Gene,Species,log_2 fold change,Adjusted p-value,t-statistic
0,E-GEOD-20168,'Parkinson's disease' vs 'normal',ENSG00000164830,homo sapiens,-2.1,5.405069e-03,NaN
1,E-GEOD-20333,'Parkinson's disease' vs 'control',ENSG00000170345,homo sapiens,-1.5,4.359893e-02,NaN
2,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'globus p...,ENSG00000104722,homo sapiens,-2.9,1.092310e-02,NaN
3,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'nucleus ...,ENSG00000133048,homo sapiens,2.6,1.397608e-02,NaN
4,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'putamen',ENSG00000143546,homo sapiens,3.1,6.409417e-04,NaN
5,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,ENSG00000145248,homo sapiens,-3.3,1.840811e-02,NaN
6,E-GEOD-7307,'Parkinson's disease' vs 'normal' in 'substant...,ENSG00000145248,homo sapiens,-4.5,1.116404e-04,NaN
7,E-GEOD-7621,'Parkinson's disease' vs 'none',ENSG00000165646,homo sapiens,-3.0,8.972822e-03,NaN
8,E-MEXP-1416,'male' vs 'female' in 'Parkinson's disease',ENSG00000229807,homo sapiens,-7.9,6.034116e-05,NaN
9,E-MTAB-9950,'Parkinson's disease' vs 'normal' in 'female',ENSG00000278384,homo sapiens,-1.7,6.760552e-03,NaN
10,E-MTAB-9950,'Parkinson's disease' vs 'normal' in 'male',ENSG00000253320,homo sapiens,-1.8,4.972942e-09,NaN

#### - Focus on one comparison experiment 'Parkinson's disease' vs 'normal' in 'substantia nigra pars reticulata'

In [12]:
condition = ["'Parkinson's disease' vs 'control'"]
filtered_df = all_df[all_df['Comparison'].isin(condition)]

In [13]:
filtered_df

,Gene,Species,Experiment accession,Comparison,log_2 fold change,Adjusted p-value,t-statistic
692,ENSG00000170345,homo sapiens,E-GEOD-20333,'Parkinson's disease' vs 'control',-1.5,0.043599,NaN

In [14]:
filtered_df['Experiment accession'].value_counts()

E-GEOD-20333    1
Name: Experiment accession, dtype: int64

#### Python script roadmap

- user inputs Experiment ID and interested group ID for that experiment
- download and save tsv file for experiment ID through requests module and ftp site
- convert tsv file into pandas dataframe
- pandas dataframe to sql

```
class Group1:
    @staticmethod
    def get_regulation(self, experiment_id: str, group_id: str) -> Dict:
        """Get all up/down regulated gene ids.
        Returns
        ------
        hgnc_ids : Dict
        """
        return {"up": ["HGNC687", "HGNC6383"], "down": ["HGNC6295", "HGNC6387"]}
 ```

In [15]:
import pandas as pd
from typing import Dict,List,Tuple
import csv
import requests

In [16]:
#experiment_id = 'E-GEOD-20168'
#group_id = 'g2_g1'
def get_regulation(experiment_id:str,group_id:str)->Dict:
    """Returns up and down regulated gene names"""
    return

In [2]:
experiment_id = 'E-GEOD-7307'
url = "http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/{id}/{id}_A-AFFY-44-analytics.tsv".format(id=experiment_id)
df = pd.read_csv(url,sep='\t')

In [3]:
df

,Gene ID,Gene Name,Design Element,g12_g5.p-value,g12_g5.t-statistic,g12_g5.log2foldchange,g12_g6.p-value,g12_g6.t-statistic,g12_g6.log2foldchange,g3_g2.p-value,...,g78_g21.log2foldchange,g82_g16.p-value,g82_g16.t-statistic,g82_g16.log2foldchange,g83_g17.p-value,g83_g17.t-statistic,g83_g17.log2foldchange,g88_g101.p-value,g88_g101.t-statistic,g88_g101.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.971106,0.318608,0.0,1.066129e-03,-5.150820,-0.5,NaN,...,0.1,0.116127,-2.070131,-0.6,0.095392,-2.262206,-0.5,0.128541,-2.115570,-0.7
1,ENSG00000000005,TNMD,220065_at,0.980500,-0.200143,0.0,NaN,0.105347,0.0,NaN,...,-2.1,NaN,1.173922,0.3,0.937077,0.109329,0.0,0.079293,-2.517706,-2.2
2,ENSG00000000419,DPM1,202673_at,0.845530,-1.252331,-0.2,5.133205e-01,0.785594,0.1,NaN,...,0.3,NaN,-2.310452,-0.5,NaN,-2.476243,-0.4,0.757479,-0.429641,-0.1
3,ENSG00000000457,SCYL3,205607_s_at,0.958495,0.430481,0.0,2.031028e-05,8.714499,0.9,NaN,...,0.2,NaN,1.837992,0.3,NaN,0.078981,0.0,0.902773,0.178371,0.0
4,ENSG00000000460,C1orf112,220840_s_at,0.850386,1.215919,0.1,7.425598e-08,-17.388069,-1.4,NaN,...,1.3,NaN,0.748839,0.2,NaN,-0.091472,0.0,NaN,0.878721,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21211,ENSG00000288611,NPBWR1,231752_at,0.997469,0.045068,0.0,3.895380e-01,1.036391,0.1,NaN,...,-0.1,NaN,2.305287,0.4,0.004154,5.625858,0.9,0.751258,-0.440696,-0.2
21212,ENSG00000288642,CDR1,207276_at,0.975081,0.246033,0.0,NaN,1.617460,0.1,NaN,...,-0.1,NaN,-0.900018,-0.2,NaN,1.131807,0.3,0.230260,-1.632254,-0.6
21213,ENSG00000288649,ACTL10,232619_at,0.997469,0.038831,0.0,1.215936e-01,1.924384,0.3,NaN,...,0.1,NaN,0.263726,0.0,NaN,2.120215,0.4,0.131633,-2.096190,-0.5
21214,ENSG00000288658,NaN,238727_at,0.886111,-0.979170,-0.1,2.692051e-02,-2.935389,-0.2,NaN,...,0.3,0.032922,-3.347352,-0.8,0.070022,-2.509723,-0.5,NaN,-1.355525,-0.2
21215,ENSG00000288701,PRRC2B,212068_s_at,0.962468,0.381901,0.0,1.181194e-04,6.958088,0.6,NaN,...,-0.1,NaN,1.080686,0.2,NaN,0.288823,0.0,NaN,-2.550236,-0.5

In [ ]:
class Group1:
    @staticmethod
    def get_up_and_down_regulated_hgnc_symbols(experiment_id: str, 
                       group_id: str,
                       threshold_p_value: float = 0.05,
                       threshold_log2fold_change: float = 1) -> Dict[list, list]:
        """Get all up/down regulated HGNC gene symbols.
        Returns
        ------ 
        hgnc_symbols : Dict
        """
        dummy_dict = {"p_value":[0.026579, 0.021427, 0.032012, 0.049699, 0.039589, 0.020602, 0.032129], 
                      "log2foldchange": [1.1, -1.7, 0.4, -1.3, -1.4, 0.6, -0.9], 
                      "gene_name": ["MKNK2", "TAC1", "TMEM176A", "MDH1", "GABRA1", "RBM6", "NDUFAB1"]}
        df = pd.DataFrame(dummy_dict)
        
        assert threshold_log2fold_change > 0
        upreg_genes = df[(df.p_value < threshold_p_value) & (df.log2foldchange > threshold_log2fold_change)]
        downreg_genes = df[(df.p_value < threshold_p_value) & (df.log2foldchange < -threshold_log2fold_change)]

        regulated_genes = {"up": upreg_genes["gene_name"].tolist(),
                           "down": downreg_genes["gene_name"].tolist()}
                    
        return regulated_genes

In [3]:
#download tsv file for respective experiment ID

parkinson_exp_dict = {'E-GEOD-7307':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-7307/E-GEOD-7307_A-AFFY-44-analytics.tsv',
                    'E-MEXP-1416':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-MEXP-1416/E-MEXP-1416_A-AFFY-54-analytics.tsv',
                     'E-GEOD-7621':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-7621/E-GEOD-7621_A-AFFY-44-analytics.tsv',
                     'E-GEOD-20168':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-20168/E-GEOD-20168_A-AFFY-33-analytics.tsv',
                     'E-GEOD-20333':'http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-20333/E-GEOD-20333_A-AFFY-41-analytics.tsv'}

def data_reader(experiment_id:str):
    if experiment_id in parkinson_exp_dict:
        url = parkinson_exp_dict[experiment_id]
#         print(url)
        df = pd.read_csv(url,sep='\t')
        
        return df
    else:
        raise ValueError ("Experiment ID does not belong to Parkinson's disease")

In [5]:
data_reader('E-GEOD-20168')

http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-20168/E-GEOD-20168_A-AFFY-33-analytics.tsv

,Gene ID,Gene Name,Design Element,g2_g1.p-value,g2_g1.t-statistic,g2_g1.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.623090,0.785727,0.2
1,ENSG00000000005,TNMD,220065_at,NaN,2.179824,0.2
2,ENSG00000000419,DPM1,202673_at,0.033769,-3.595145,-1.0
3,ENSG00000000457,SCYL3,205607_s_at,NaN,-0.899866,-0.1
4,ENSG00000000460,C1orf112,220840_s_at,NaN,2.572624,0.1
...,...,...,...,...,...,...
12051,ENSG00000287080,H3C3,208577_at,NaN,1.609577,0.1
12052,ENSG00000288569,LINC01949,217342_x_at,NaN,2.409303,0.2
12053,ENSG00000288596,C8orf44,220216_at,NaN,0.950915,0.1
12054,ENSG00000288642,CDR1,207276_at,0.132890,-2.375270,-0.3
12055,ENSG00000288701,PRRC2B,212068_s_at,0.657188,0.714372,0.1

In [2]:
url = "http://ftp.ebi.ac.uk/pub/databases/microarray/data/atlas/experiments/E-GEOD-7307/E-GEOD-7307_A-AFFY-44-analytics.tsv"
df = pd.read_csv(url,sep='\t')
df.head()

,Gene ID,Gene Name,Design Element,g12_g5.p-value,g12_g5.t-statistic,g12_g5.log2foldchange,g12_g6.p-value,g12_g6.t-statistic,g12_g6.log2foldchange,g3_g2.p-value,...,g78_g21.log2foldchange,g82_g16.p-value,g82_g16.t-statistic,g82_g16.log2foldchange,g83_g17.p-value,g83_g17.t-statistic,g83_g17.log2foldchange,g88_g101.p-value,g88_g101.t-statistic,g88_g101.log2foldchange
0,ENSG00000000003,TSPAN6,209108_at,0.971106,0.318608,0.0,1.066129e-03,-5.150820,-0.5,NaN,...,0.1,0.116127,-2.070131,-0.6,0.095392,-2.262206,-0.5,0.128541,-2.115570,-0.7
1,ENSG00000000005,TNMD,220065_at,0.980500,-0.200143,0.0,NaN,0.105347,0.0,NaN,...,-2.1,NaN,1.173922,0.3,0.937077,0.109329,0.0,0.079293,-2.517706,-2.2
2,ENSG00000000419,DPM1,202673_at,0.845530,-1.252331,-0.2,5.133205e-01,0.785594,0.1,NaN,...,0.3,NaN,-2.310452,-0.5,NaN,-2.476243,-0.4,0.757479,-0.429641,-0.1
3,ENSG00000000457,SCYL3,205607_s_at,0.958495,0.430481,0.0,2.031028e-05,8.714499,0.9,NaN,...,0.2,NaN,1.837992,0.3,NaN,0.078981,0.0,0.902773,0.178371,0.0
4,ENSG00000000460,C1orf112,220840_s_at,0.850386,1.215919,0.1,7.425598e-08,-17.388069,-1.4,NaN,...,1.3,NaN,0.748839,0.2,NaN,-0.091472,0.0,NaN,0.878721,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21211,ENSG00000288611,NPBWR1,231752_at,0.997469,0.045068,0.0,3.895380e-01,1.036391,0.1,NaN,...,-0.1,NaN,2.305287,0.4,0.004154,5.625858,0.9,0.751258,-0.440696,-0.2
21212,ENSG00000288642,CDR1,207276_at,0.975081,0.246033,0.0,NaN,1.617460,0.1,NaN,...,-0.1,NaN,-0.900018,-0.2,NaN,1.131807,0.3,0.230260,-1.632254,-0.6
21213,ENSG00000288649,ACTL10,232619_at,0.997469,0.038831,0.0,1.215936e-01,1.924384,0.3,NaN,...,0.1,NaN,0.263726,0.0,NaN,2.120215,0.4,0.131633,-2.096190,-0.5
21214,ENSG00000288658,NaN,238727_at,0.886111,-0.979170,-0.1,2.692051e-02,-2.935389,-0.2,NaN,...,0.3,0.032922,-3.347352,-0.8,0.070022,-2.509723,-0.5,NaN,-1.355525,-0.2
21215,ENSG00000288701,PRRC2B,212068_s_at,0.962468,0.381901,0.0,1.181194e-04,6.958088,0.6,NaN,...,-0.1,NaN,1.080686,0.2,NaN,0.288823,0.0,NaN,-2.550236,-0.5

In [13]:
df.head()

,Gene ID,Gene Name,Design Element,g2_g1.p-value,g2_g1.t-statistic,g2_g1.log2foldchange,g4_g3.p-value,g4_g3.t-statistic,g4_g3.log2foldchange
0,ENSG00000000003,TSPAN6,g2995860_3p_at,NaN,1.703524,1.0,0.522520,1.241137,0.9
1,ENSG00000000005,TNMD,g11545882_3p_at,NaN,-0.329159,-0.1,NaN,0.575565,0.1
2,ENSG00000000419,DPM1,g4503362_3p_at,NaN,2.286994,2.0,0.997115,-0.006181,0.0
3,ENSG00000000457,SCYL3,g9967093_3p_s_at,NaN,1.762578,1.6,0.723872,0.678925,0.4
4,ENSG00000000460,C1orf112,g8922604_3p_a_at,NaN,-1.018646,-0.1,NaN,-0.285732,-0.1